# Consider shell executor for deployment. Runs commands directly onhost machine.
# Consider docker executor for build and test jobs. Runs commands in isolated containers.
default:
  image: python:3.11-slim
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate

stages: # stages contain jobs
  - test
  - deploy

# Share tests to distinct jobs
unit_tests:
  stage: test
  script:
    - echo "Running unit tests..."
    - pytest tests/unit_tests
  tags:
    - shared-runner

integration_tests:
  stage: test
  script:
    - echo "Running integration tests..."
    - pytest tests/integration_tests/test_construct_retina_cpu.py
    - pytest tests/integration_tests/test_simulation.py
    - pytest tests/integration_tests/test_visual_stimulus.py
  tags:
    - shared-runner

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  tags:
    - shared-runner
