image: python:3.11-slim

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building job..."
    - pip install poetry
  tags:
    - shared-runner

test-job1:
  stage: test
  script:
    - echo "Running test 1..."
  tags:
    - shared-runner
  dependencies:
    - build-job    
test-job2:
  stage: test
  script:
    - echo "Running test 2..."
  tags:
    - shared-runner
test-job3:
  stage: test
  script:
    - echo "Running test 3..."
  tags:
    - shared-runner
test-job4:
  stage: test
  script:
    - echo "Running test 4..."
  tags:
    - shared-runner 
test-job5:
  stage: test
  script:
    - echo "Running test 5..."
  tags:
    - shared-runner

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"  
  tags:
    - shared-runner
