image: python:3.11-slim

build-job:
  stage: build
  script:
    - echo "Building the project..."
    - pip install poetry
    - poetry install
  tags:
    - shared-runner

test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - pytest tests/unit_tests/test_project_utilities.py
  tags:
    - shared-runner


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  tags:
    - shared-runner
