default:
  image: python:3.12-slim
  before_script:
    - export PATH=/tmp/.local/bin:$PATH
    - pip install poetry
    - poetry install --without dev
    - VENV_PATH=$(poetry env info --path)
    - source "$VENV_PATH/bin/activate"
    - pip install pyyaml

stages: # stages contain jobs
  # - test
  - deploy

# # Share tests to distinct jobs
# unit_tests:
#   stage: test
#   script:
#     - echo "Running unit tests..."
#     - pytest tests/unit_tests -v
#   tags:
#     - openshift
#   variables:
#     HOME: /tmp

# integration_tests1:
#   stage: test
#   script:
#     - echo "Running integration tests..."
#     - pytest tests/integration_tests/test_construct_retina_cpu.py -v
#   tags:
#     - openshift
#   variables:
#     HOME: /tmp

# integration_tests2:
#   stage: test
#   script:
#     - echo "Running integration tests..."
#     - pytest tests/integration_tests/test_simulation_cpu.py -v
#     - pytest tests/integration_tests/test_visual_stimulus.py -v
#   tags:
#     - openshift
#   variables:
#     HOME: /tmp


deploy-prod:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/ci-cd/ssh-client:latest
  # image: bitnami/git:latest  # This image has git and ssh
  before_script: []  # Override the default before_script
  script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$GITHUB_DEPLOY_KEY_BASE64" | base64 -d > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-add ~/.ssh/id_ed25519
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git remote add github git@github.com:VisualNeuroscience-UH/macaqueretina.git
    - git remote -v
    - ssh -Tv git@github.com
    - echo "Deploying to production..."
    - git fetch --dry-run
    - git push --dry-run github continuous_deployment:continuous_deployment
    - echo "Dry run successful. Proceeding with actual deployment..."
    # - git push github +$CI_COMMIT_SHA:continuous_deployment
  variables:
    HOME: /tmp
  rules:
    - if: $CI_COMMIT_REF_NAME == "continuous_deployment"
  tags:
    - openshift
