# Consider shell executor for deployment. Runs commands directly onhost machine.
# Consider docker executor for build and test jobs. Runs commands in isolated containers.
default:
  image: python:3.11-slim
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate

stages: # stages contain jobs
  - test
  - deploy

test-job1:
  stage: test
  script:
    - echo "Running test 1..."
    - pytest
  tags:
    - shared-runner

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"  
  tags:
    - shared-runner
