default:
  image: python:3.12-slim
  before_script:
    - export PATH=/tmp/.local/bin:$PATH
    - pip install poetry
    - poetry install --without dev
    - VENV_PATH=$(poetry env info --path)
    - source "$VENV_PATH/bin/activate"
    - pip install pyyaml
    - get_vae_models.sh

stages: # stages contain jobs
  - test
  - deploy

# Share tests to distinct jobs
unit_tests:
  stage: test
  script:
    - echo "Running unit tests..."
    - pytest tests/unit_tests
  tags:
    - openshift
  variables:
    HOME: /tmp

integration_tests1:
  stage: test
  script:
    - echo "Running integration tests..."
    - pytest tests/integration_tests/test_construct_retina_cpu.py
  tags:
    - openshift
  variables:
    HOME: /tmp

integration_tests2:
  stage: test
  script:
    - echo "Running integration tests..."
    - pytest tests/integration_tests/test_simulation_cpu.py
    - pytest tests/integration_tests/test_visual_stimulus.py
  tags:
    - openshift
  variables:
    HOME: /tmp


deploy-prod:
  stage: deploy
  image: bitnami/git:latest
  before_script: []
  script:
    - git remote add github https://$GITHUB_PAT@github.com/VisualNeuroscience-UH/macaqueretina.git
    - git push github "+$CI_COMMIT_SHA:continuous_deployment"
  variables:
    HOME: /tmp
    GIT_DEPTH: "0"  # Disable shallow clone
  rules:
    - if: $CI_COMMIT_REF_NAME == "continuous_deployment"
  tags:
    - openshift
