image: python:3.11-slim

before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true  # Creates the virtualenv inside the project directory

build-job:
  stage: build
  script:
    - poetry install
  tags:
    - shared-runner

test-job:
  stage: test
  script:
    - source .venv/bin/activate  # Activate the virtualenv
    - pytest tests/unit_tests/test_project_utilities.py
  tags:
    - shared-runner
       
deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  tags:
    - shared-runner
