image: docker:latest

build-job:
  stage: build
  script:
    - poetry install
  tags:
    - shared-runner

test-job:
  stage: test
  script:
    - pytest tests/unit_tests/test_project_utilities.py
  tags:
    - shared-runner


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  tags:
    - shared-runner
