[tool.poetry]
name = "macaqueretina"
version = "0.6.0"  # Replace with dynamic version extraction if possible
description = "Python software to build a model of macaque retina and convert visual stimuli to cortical input"
authors = ["Simo Vanni <simo.vanni@helsinki.fi>", "Henri Hokkanen"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/VisualNeuroscience-UH/MacaqueRetina"
repository = "https://github.com/VisualNeuroscience-UH/MacaqueRetina"
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]

[tool.poetry.dependencies]
python = "^3.11"
colorednoise = "*"
h5py = "*"
imageio = "*"
ipython = "*"
jupyterlab = "*"
matplotlib = "*"
notebook = "*"
numpy = "*"
opencv-python-headless = "*"
pandas = "*"
Pillow = "*"
pyshortcuts = "*"
scikit-image = "*"
scikit-learn = "*"
scipy = "*"
seaborn = "*"
Shapely = "*"
torch = "*"
torch-fidelity = "*"
torchmetrics = "*"
torchsummary = "*"
torchaudio = "*"
torchvision = "*"
tqdm = "*"
cython = "^3.0.11"
brian2 = "2.7.1"
pyqt5 = "^5.15.11"
brian2cuda = "^1.0a6"
isort = "*"
optuna = "*"
pytest = "*"
ray = {extras = ["tune"], version = "*"}
pydantic = "^2.11.7"
typer = "^0.16.1"

[tool.poetry.scripts]
run_macaqueretina = "project.project_conf_module:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
known_third_party = [
    "numpy", "pandas", "matplotlib", "scipy", "torch", "torchvision", 
    "torchmetrics", "torchsummary", "torchaudio", "opencv", "cv2", 
    "imageio", "seaborn", "scikit-image", "scikit-learn", "PIL", 
    "Pillow", "h5py", "Shapely", "tqdm", "colorednoise", "brian2", 
    "brian2cuda", "ray", "optuna", "ipython", "jupyterlab", 
    "notebook", "pyshortcuts"
]
known_localfolder = ["macaqueretina"]
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
default_section = "THIRDPARTY"
import_heading_stdlib = "Built-in"
import_heading_thirdparty = "Third-party"
import_heading_localfolder = "Local"